name: andmeteadus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip
  - pip:
    - plotly>=5.15.0
    - bokeh>=3.2.0
    - openpyxl>=3.1.0
    - xlrd>=2.0.0
    - statsmodels>=0.14.0
    - pytz>=2023.3
    - tqdm>=4.65.0
